#!/bin/bash
#
#
mysql=$(dpkg-query -W -f='${Status}' mysql-server 2>/dev/null | grep -c "ok installed")
if [ $mysql -eq 0 ]
then
	echo "mysql paigaldus"
	pause
	apt install mysql-client mysql-server -y

elif [ $mysql -eq 1 ]
then
	echo "mysql on paigaldatud"
	pause
	systemctl status mysql
fi
